#tomcat配置
server:
  port: 80
  servlet:
    context-path: /

spring:
#  thymeleaf 配置
  thymeleaf:
    prefix: classpath:webapps/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 禁用缓存
    cache: false
  #  jdbc配置
  datasource:
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
#    driver-class-name: com.mysql.jdbc.Driver
    url: @springbootdemo.mysql.url@
    username: @springbootdemo.mysql.username@
    password: @springbootdemo.mysql.password@
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  #  Redis配置
  redis:
    database: 0
    host: @springbootdemo.redis.host@
    port: @springbootdemo.redis.port@
    password: @springbootdemo.redis.password@
    timeout: 3000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 1000ms
  #  静态资源映射
  resources:
      static-locations:
      - classpath:webapps/

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.demo.domain

#日志配置
logging:
  level:
    root: @springbootdemo.log.level@

#自定义配置